stages:
  - lint

LintGitCommitMessages:
  stage: lint
  only:
    - main
  artifacts:
    paths:
      - gitlint.cfg
  image:
    name: python:3.9-slim
    entrypoint: [""]
  script:
    - apt-get update && apt-get install -y curl git
    - pip install gitlint
    - |      
      echo "Downloading gitlint.cfg from the ci-commons project..."
      curl --output gitlint1.cfg "${CI_API_V4_URL}/projects/fabien.launay.public%2Fci-commons/jobs/artifacts/main/raw/gitlint.cfg?job=GenerateGitlintConfig"
      echo "gitlint1.cfg:"
      curl --output gitlint2.cfg "https://gitlab.com/fabien.launay.public/ci-commons/-/raw/main/gitlint.cfg"
      echo "gitlint2.cfg:"
      echo ""
      ls -l
      echo ""
    - gitlint --config gitlint.cfg