stages:
  - linting

commit-message:
  stage: linting
  image:
    name: jorisroovers/gitlint:0.19.1
    entrypoint: [ "" ]
  script:
    - . .ci/common.bash
    - |
      #
      echo -e $BLUE"BLUE"
      echo -e "#########################"      
      echo -e "#        Gitlint        #"
      echo -e "#########################"
      echo -e "$NO_COLOR"
    - exit_code=0
    - RESULT=$(gitlint 2>&1) || exit_code=$?
    - handle_test_result $exit_code "$RESULT"
    - exit $exit_code
  needs: [ ]