stages:
  - linting

commit-message:
  stage: linting
  image:
    name: jorisroovers/gitlint:0.19.1
    entrypoint: [""]
  script:
    - . .ci/common.bash
    - title "*** Running gitlint..."
    - exit_code=0
    - RESULT=$(gitlint 2>&1) || exit_code=$?
    - handle_test_result $exit_code "$RESULT"
    - exit $exit_code
  needs: []