stages:
  - generate-config
  - lint

GenerateGitlintConfig:
  stage: generate-config
  script:
    - echo "TEST"
  artifacts:
    paths:
      - gitlint.cfg

LintGitCommitMessages:
  stage: lint
  only:
    - main
  dependencies:
    - GenerateGitlintConfig
  image:
    name: python:3.9-slim
    entrypoint: [""]
  script:
    - apt-get update && apt-get install -y curl git
    - pip install gitlint
    - |      
      echo "Downloading gitlint.cfg from the ci-commons project..."
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --output gitlint1.cfg "${CI_API_V4_URL}/projects/fabien.launay.public%2Fci-commons/jobs/artifacts/main/raw/gitlint.cfg?job=GenerateGitlintConfig"
      echo "################################"
      echo "gitlint1.cfg"
      echo "################################"
      cat gitlint1.cfg
      echo ""
      curl --output gitlint2.cfg "https://gitlab.com/fabien.launay.public/ci-commons/-/raw/main/gitlint.cfg"
      echo "################################"
      echo "gitlint2.cfg"
      echo "################################"
      cat gitlint2.cfg
      echo ""
      ls -l
      echo ""
    - gitlint --config gitlint.cfg