#!/bin/bash

. ci-commons/tools/common/bsh/message.bash

# ==============================================================================
# Abort if Git pre-commit hook failed
# ==============================================================================

LOCK_FILE="tools/git/hooks/pre-commit-failed"

if [ -f "$LOCK_FILE" ]; then
  exit 1
fi

# ==============================================================================
# Print header
# ==============================================================================

printLargeTextBoxForGitHooks "Commit Message Hook"

currentL1TaskNumber="1"
totalL1TaskCount="2"

# ==============================================================================
# Prefix Git commit message title with emoji
# ==============================================================================

python='C:\ProgramFiles\Code\Python\python.exe'
if [ ! -x "$python" ]; then
  echo 'python not found.' 1>&2
  exit 1
fi

printStartingL1TaskTextBox "prefix Git commit message title with emoji"

command="$python
  ci-commons/tools/git/hooks/py/emojiPrefix.py
  $1"
printExecutingCommand "$command"
$command

if [[ $? -ne 0 ]]; then
  printCompletedL1TaskTextBoxAndIncrementCounter
  exit 1
fi
printCompletedL1TaskTextBoxAndIncrementCounter

# ==============================================================================
# Lint Git commit message
# ==============================================================================

printStartingL1TaskTextBox "linting of Git commit message"

cd ci-commons
echo "[commit-msg] Execution path: '$(pwd)'"

command="gitlint
  --config tools/gitlint/gitlint.cfg
  --msg-filename ../$1"
printExecutingCommand "$command"
$command

if [[ $? -ne 0 ]]; then
  echo ''
  printErrorMessage "Git commit message linting failed. Please fix the issues listed above."
  printCompletedL1TaskTextBoxAndIncrementCounter
  exit 1
fi

printCompletedL1TaskTextBoxAndIncrementCounter