stages:
  - lint
  - build

Lint-ci-commons-project:
  stage: lint
  rules:
    - if: '$CI_PROJECT_NAME == "ci-commons" && $CI_COMMIT_BRANCH == "main"'
  image:
    name: python:3.9-slim
    entrypoint: [""]
  script:
    - apt-get update && apt-get install -y git
    - pip install gitlint
    - gitlint --config cfg/gitlint/gitlint.cfg

Lint:
  stage: lint
  rules:
    - if: '$CI_PROJECT_NAME != "ci-commons" && $CI_COMMIT_BRANCH == "main"'
  image:
    name: python:3.9-slim
    entrypoint: [""]
  script:
    - apt-get update && apt-get install -y curl unzip git
    - pip install gitlint
    - |
      if [ ! -f cfg/gitlint/gitlint.cfg ]; then
        echo "Downloading artifacts.zip from 'ci-commons' project..."        
        curl \
          --location \
          --header "PRIVATE-TOKEN: $CI_PERSONAL_ACCESS_TOKEN" \
          --output artifacts.zip \
          "https://gitlab.com/api/v4/projects/56935262/jobs/artifacts/main/download?job=Generate_artifacts"
        unzip artifacts.zip
      fi
    - gitlint --config cfg/gitlint/gitlint.cfg

Generate_artifacts:
  stage: build
  rules:
    - if: '$CI_PROJECT_NAME == "ci-commons" && $CI_COMMIT_BRANCH == "main"'
  script:
    - echo "Generating artifacts..."
  artifacts:
    paths:
      - cfg/gitlint/

