include:
  - local: .gitlab/01_Stages/stages.yml
  - local: .gitlab/02_Variables/variables.yml
  - local: .gitlab/03_Stages/01_LintGitCommitMessages/lintGitCommitMessagesForSelf.yml
  - local: .gitlab/03_Stages/01_LintGitCommitMessages/lintGitCommitMessagesForCaller.yml

#-------------------------------------------------------------------------------
# Generate Artifacts
#-------------------------------------------------------------------------------
Generate-Artifacts:
  stage: build
  rules:
    # Trigger job on push to main branch.
    - if: >
        $CI_PROJECT_NAME == $PROJECT_NAME &&
        $CI_PIPELINE_SOURCE == "push" &&
        $CI_COMMIT_BRANCH == "main"
    # Trigger job on merge request to main branch.
    - if: >
        $CI_PROJECT_NAME == $PROJECT_NAME &&
        $CI_PIPELINE_SOURCE == "merge_request_event" &&
        $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
  script:
    - echo "Generating artifacts..."
  artifacts:
    paths:
      - bsh/
      - cfg/