stages:
  - lint

LintGitCommitMessages:
  stage: lint
  image:
    name: jorisroovers/gitlint:0.19.1
    entrypoint: [ "" ]
  script:
    - gitlint --config cfg/gitlint/gitlint.cfg
  only:
    - main
  artifacts:
    paths:
      - cfg/gitlint/gitlint.cfg