stages:
  - lint
  - build

Lint-ci-commons-project:
  stage: lint
  rules:
    # Trigger on push to main branch
    - if: '$CI_PROJECT_NAME == "ci-commons" && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
  # Trigger on merge request to main branch
    - if: '$CI_PROJECT_NAME == "ci-commons" && $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
  image:
    name: python:3.9-slim
    entrypoint: [""]
  before_script:
    - bash bsh/lintCiCommonsProjectBeforeScript.bash "git"
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
        bash bsh/lintCiCommonsProjectScript.bash \
          "$CI_COMMIT_BEFORE_SHA" \
          "$CI_COMMIT_SHA" 
      elif [[ "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" == "main" ]]; then
        bash bsh/lintCiCommonsProjectScript.bash \
          "$CI_MERGE_REQUEST_DIFF_BASE_SHA" \
          "$CI_COMMIT_SHA"        
      fi

Lint:
  stage: lint
  rules:
    # Trigger on push to main branch
    #- if: '$CI_PROJECT_NAME != "ci-commons" && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
    # Trigger on merge request to main branch
    - if: '$CI_PROJECT_NAME != "ci-commons" && $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'

  image:
    name: python:3.9-slim
    entrypoint: [""]
  before_script:
     - apt-get update
     - apt-get install --yes curl unzip git
  script:
    - |      
      curl \
        --verbose \
        --location \
        --header "PRIVATE-TOKEN: $CI_PERSONAL_ACCESS_TOKEN" \
        --output artifacts.zip \
          "https://gitlab.com/api/v4/projects/56935262/jobs/artifacts/main/download?job=Generate-artifacts"
      unzip artifacts.zip
      bash bsh/lintCiCommonsProjectScript.bash \
        "$CI_MERGE_REQUEST_DIFF_BASE_SHA" \
        "$CI_COMMIT_SHA"


Generate-artifacts:
  stage: build
  rules:
    # Trigger on push to main branch
    - if: '$CI_PROJECT_NAME == "ci-commons" && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
    # Trigger on merge request to main branch
    - if: '$CI_PROJECT_NAME == "ci-commons" && $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
  script:
    - echo "Generating artifacts..."
  artifacts:
    paths:
      - bsh/
      - cfg/

