stages:
  - generate-config
  - lint

GenerateGitlintConfig:
  stage: generate-config
  rules:
    - if: '$CI_PROJECT_NAME == "ci-commons"'
  only:
    - main
  script:
    - echo "TEST"
  artifacts:
    paths:
      - cfg/gitlint/

LintGitCommitMessages:
  stage: lint
  rules:
    - if: '$CI_PROJECT_NAME != "ci-commons"'
  only:
    - main
  image:
    name: python:3.9-slim
    entrypoint: [""]
  script:
    - apt-get update && apt-get install -y curl git unzip
    - pip install gitlint
    - |
      if [ ! -f cfg/gitlint/gitlint.cfg ]; then
        echo "Downloading artifacts.zip from the ci-commons project..."        
        curl \
          --location \
          --header "PRIVATE-TOKEN: $CI_PERSONAL_ACCESS_TOKEN" \
          --output artifacts.zip \
          "https://gitlab.com/api/v4/projects/56935262/jobs/artifacts/main/download?job=GenerateGitlintConfig"
        unzip artifacts.zip
      fi
    - gitlint --config cfg/gitlint/gitlint.cfg