stages:
  - lint
  - build

Lint-ci-commons-project:
  stage: lint
  rules:
    # Trigger on push to main branch
    - if: '$CI_PROJECT_NAME == "ci-commons" && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
  # Trigger on merge request to main branch
    - if: '$CI_PROJECT_NAME == "ci-commons" && $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
  image:
    name: python:3.9-slim
    entrypoint: [""]
  before_script:
    - bash bsh/lintCiCommonsProjectBeforeScript.bash
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
        bash bsh/lintCiCommonsProjectScript.bash \
          "$CI_COMMIT_BEFORE_SHA" \
          "$CI_COMMIT_SHA" 
      elif [[ "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" == "main" ]]; then
        bash bsh/lintCiCommonsProjectScript.bash \
          "$CI_MERGE_REQUEST_DIFF_BASE_SHA" \
          "$CI_COMMIT_SHA"        
      fi

Lint:
  stage: lint
  rules:
    # Trigger on push to main branch
    #- if: '$CI_PROJECT_NAME != "ci-commons" && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
    # Trigger on merge request to main branch
    - if: '$CI_PROJECT_NAME != "ci-commons" && $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'

  image:
    name: python:3.9-slim
    entrypoint: [""]
  before_script:
    - apt-get update
    - apt-get install -y curl unzip git
    - pip install gitlint
  script:
    - |
      if [ ! -f cfg/gitlint/gitlint.cfg ]; then
        echo "==========================="
        echo "Listing all jobs with artifacts in the main branch using https://gitlab.com/api/v4/projects/56935262/jobs/artifacts/main"
        echo "==========================="
        curl \
          --verbose \
          --location \
          --header "PRIVATE-TOKEN: $CI_PERSONAL_ACCESS_TOKEN" \
            "https://gitlab.com/api/v4/projects/56935262/jobs/artifacts/main"
        echo "==========================="
        echo "Listing all jobs with artifacts in the main branch using https://gitlab.com/api/v4/projects/56935262/jobs/artifacts/main"
        echo "==========================="
          curl \
            --verbose \
            --location \
            --header "PRIVATE-TOKEN: $CI_PERSONAL_ACCESS_TOKEN" \
              "https://gitlab.com/fabien.launay/ci-commons/jobs/artifacts/main"
        echo "==========================="
        echo "Downloading artifacts.zip from 'ci-commons' project... using "https://gitlab.com/api/v4/projects/56935262/jobs/artifacts/main/download?job=Generate-artifacts""
        echo "==========================="
        curl \
          --verbose \
          --location \
          --header "PRIVATE-TOKEN: $CI_PERSONAL_ACCESS_TOKEN" \
          --output artifacts1.zip \
            "https://gitlab.com/api/v4/projects/56935262/jobs/artifacts/main/download?job=Generate-artifacts"
        echo "==========================="
        echo "Downloading artifacts.zip from 'ci-commons' project... using https://gitlab.com/fabien.launay/ci-commons/jobs/artifacts/main/download?job=Generate-artifacts"
        echo "==========================="
        curl \
          --verbose \
          --location \
          --header "PRIVATE-TOKEN: $CI_PERSONAL_ACCESS_TOKEN" \
          --output artifacts2.zip \
            "https://gitlab.com/fabien.launay/ci-commons/jobs/artifacts/main/download?job=Generate-artifacts"
        echo "==========================="
        ls -la
        echo "==========================="
        echo "cat artifacts1.zip"
        echo "==========================="
        cat artifacts1.zip
        echo "==========================="
        echo "cat artifacts2.zip"
        echo "==========================="
        cat artifacts2.zip
        echo "==========================="
        echo "unzip artifacts1.zip"
        echo "==========================="
        unzip artifacts1.zip
        echo "==========================="
        echo "unzip artifacts2.zip"
        echo "==========================="
        unzip artifacts2.zip
      fi
      bash bsh/lintCiCommonsProjectScript.bash \
        "$CI_MERGE_REQUEST_DIFF_BASE_SHA" \
        "$CI_COMMIT_SHA"

Generate-artifacts:
  stage: build
  rules:
    # Trigger on push to main branch
    - if: '$CI_PROJECT_NAME == "ci-commons" && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
    # Trigger on merge request to main branch
    - if: '$CI_PROJECT_NAME == "ci-commons" && $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
  script:
    - echo "Generating artifacts..."
  artifacts:
    paths:
      - cfg/gitlint/

