---
# #############################################################################
# Copyright (C) 2023-2024 Fabien Launay. All Rights Reserved.
# Author: Fabien Launay.
# Email : fabien.launay.email@gmail.com.
# Source: This file is part of the "Reactor Coding Challenge 01" project Git
#         repository developed by Fabien Launay for Woven by Toyota.
# Usage : This copyright notice may not be removed from this file.
# #############################################################################
# #############################################################################
# This file describes what repositories and pre-commit hooks are installed as
# plugins for the pre-commit framework.
#
# For more details, please refer to the following section in the pre-commit
# package manager home page:
#  - Name: Adding pre-commit plugins to your project
#  - Link: https://pre-commit.com/#adding-pre-commit-plugins-to-your-project
#
# Remark: The global default file include override patterns use python verbose
# regular expression to enhance their readability.
#
# For more details, please refer to the following section in the pre-commit
# package manager home page:
#  - Name: Regular expressions
#  - Link: https://pre-commit.com/#regular-expressions
# #############################################################################

repos:
  #############################################################################
  # Check spelling in text files
  #############################################################################
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        name: <01/16> Check spelling in text files.
        exclude: '(CHANGELOG.pdf|cfg/gitlint/txt/Verbs.txt)'
        args:
          - --ignore-words=cfg/codespell/ignoreWords.txt

  #############################################################################
  # Format and Lint CMake files
  #############################################################################
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:

      #==========================================================================
      # Format CMake files
      #==========================================================================
      - id: cmake-format
        name: <02/16> Format CMake files.

      #==========================================================================
      # Lint CMake files
      #==========================================================================
      - id: cmake-lint
        name: <03/16> Lint CMake files.

  #############################################################################
  # Insert license
  #############################################################################
  #============================================================================
  # USAGE: To update the comment headers introduced by insert-license hook:
  #
  # 1.Temporarily uncomment the `--remove-header` arg in the `args` list of the
  #  hooks whose `id` is equal to `insert-license`.
  #
  # 2.Run the `insert-license` hook on all files:
  #   ------------------------------------------------------------------------
  #   pre-commit run insert-license \
  #              --config cfg/pre-commit/preCommitConfig.yaml \
  #              --all-files
  #   ------------------------------------------------------------------------
  #
  # 3.Comment the temporarily uncommented `--remove-header` arg.
  #
  # 4.Update the `lic/Copyright.txt` file.
  #
  # 5. Re-run the `insert-license` hook on all files.
  #============================================================================
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:

      #==========================================================================
      # Insert copyright notice text block in "#" comment style
      #==========================================================================
      - id: insert-license
        name: <04/16> Insert copyright notice text block in "#" comment style.
        files: |
          (?x)^(
            \.gitignore|
            .*\.yaml|
            CPPLINT\.cfg|
            .*CMakeLists\.txt|
            .*\.cmake|
            .*\.bash
          )$
        args:
          # - --remove-header
          - --license-filepath
          - lic/Copyright.txt
          - --use-current-year
          - --fuzzy-match-generates-todo

      #==========================================================================
      # Insert copyright notice text block in "//" comment style
      #==========================================================================
      - id: insert-license
        name: <05/16> Insert copyright notice text block in "//" comment style.
        files: |
          (?x)^(
            .*\.cpp|
            .*\.hpp|
            cfg/cppcheck/suppressions.txt
          )$
        args:
          # - --remove-header
          - --license-filepath
          - lic/Copyright.txt
          - --comment-style
          - //
          - --use-current-year
          - --fuzzy-match-generates-todo

      #==========================================================================
      # Insert copyright notice text block in "<!--" comment style
      #==========================================================================
      - id: insert-license
        name: <06/16> Insert copyright notice text block in "<!--" comment style.
        files: |
          (?x)^(
            .*\.md
          )$
        args:
          # - --remove-header
          - --license-filepath
          - lic/Copyright.txt
          - --comment-style
          - <!--|  ~|  -->
          - --use-current-year
          - --fuzzy-match-generates-todo

      #==========================================================================
      # Insert copyright notice text block in "'{#|" comment style
      #==========================================================================
      - id: insert-license
        name: <07/16> Insert copyright notice text block in "'{#|" comment style.
        files: |
          (?x)^(
            .*\.jinja
          )$
        args:
          # - --remove-header
          - --license-filepath
          - lic/Copyright.txt
          - --comment-style
          - '{#||#}'
          - --use-current-year
          - --fuzzy-match-generates-todo

      #==========================================================================
      # Insert copyright notice text block in "'" comment style
      #==========================================================================
      - id: insert-license
        name: <08/16> Insert copyright notice text block in "'" comment style.
        files: |
          (?x)^(
            .*\.puml
          )$
        args:
          # - --remove-header
          - --license-filepath
          - lic/Copyright.txt
          - --comment-style
          - "'"
          - --use-current-year
          - --fuzzy-match-generates-todo

  #############################################################################
  # Format Markdown files
  #############################################################################
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        name: <09/16> Format Markdown files.
        files: |
          (?x)^(
            .*\.md
          )$

  #############################################################################
  # Format YAML files
  #############################################################################
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        name: <10/16> Format YAML files.
        files: |
          (?x)^(
            .*\.yaml
          )$

  #############################################################################
  # Format JSON files
  #############################################################################
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: pretty-format-json
        name: <11/16> Format JSON files.
        args:
          - --autofix
          - --no-sort-keys

  #############################################################################
  # Check CMake system and user presets JSON files against their schema.
  #############################################################################

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.0
    hooks:
      - id: check-jsonschema
        name: <12/16> Check CMake system and user presets JSON files against their schema.
        files: |
          (?x)^(
            CMakePresets\.json|
            CMakeUserPresets\.json
          )$
        args:
          - --schemafile=cmk/presetsSchemaDefinition.json

  #############################################################################
  # Format Bash script files
  #############################################################################
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.7.0-4
    hooks:
      - id: shfmt
        name: <13/16> Format Bash script files.
        files: |
          (?x)^(
            .*\.bash
          )$

  #############################################################################
  # Format and perform static analysis on C++ source code
  #############################################################################
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:

      #==========================================================================
      # Format C++ header and source files according to Google C++ Style Guide
      #==========================================================================
      - id: clang-format
        name: <14/16> Format C++ header and source files according to Google C++ Style Guide.
        args:
          - --style=Google
          - -i

      #==========================================================================
      # Check C++ header and source files style against Google's C++ style guide
      #==========================================================================
      - id: cpplint
        name: <15/16> Check C++ header and source files style against Google's C++ style guide.

      #==========================================================================
      # Perform static C++ code analysis with Cppcheck
      #==========================================================================
      - id: cppcheck
        name: <16/16> Perform static C++ code analysis with Cppcheck.
        args:
          - --language=c++
          - --std=c++20
          - --suppressions-list=cfg/cppcheck/suppressions.txt
          - --library=googletest