---
# #############################################################################
# Copyright (C) 2023-2024 Fabien Launay. All Rights Reserved.
# Author: Fabien Launay.
# Email : fabien.launay.email@gmail.com.
# Source: This file is part of the "Reactor Coding Challenge 01" project Git
#         repository developed by Fabien Launay for Woven by Toyota.
# Usage : This copyright notice may not be removed from this file.
# #############################################################################
# #############################################################################
# This file describes what repositories and pre-commit hooks are installed as
# plugins for the pre-commit framework.
#
# For more details, please refer to the following section in the pre-commit
# package manager home page:
#  - Name: Adding pre-commit plugins to your project
#  - Link: https://pre-commit.com/#adding-pre-commit-plugins-to-your-project
#
# Remark: The global default file include override patterns use python verbose
# regular expression to enhance their readability.
#
# For more details, please refer to the following section in the pre-commit
# package manager home page:
#  - Name: Regular expressions
#  - Link: https://pre-commit.com/#regular-expressions
# #############################################################################

repos:
  #############################################################################
  # Check spelling in text files
  #############################################################################
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        name: <01/01> Check spelling in text files.
        exclude: >
          (ci-commons/tools/gitlint/txt/Verbs.txt|
          ci-commons/tools/codespell/ignoreWords.txt
          )
        args:
          - --ignore-words=ci-commons/tools/codespell/ignoreWords.txt