stages:
  - Lint

LintGitCommitMessages:
  description: "Verify Git commit messages with Gitlint"
  stage: Lint
  image:
    name: jorisroovers/gitlint:0.19.1
    entrypoint: [ "" ]
  script:
    - gitlint --config cfg/gitlint/gitlint.cfg
  only:
    - main
  needs: [ ]