stages:
  - Lint

LintGitCommitMessages:
  stage: Lint
  image:
    name: jorisroovers/gitlint:0.19.1
    entrypoint: [ "" ]
  script:
    - RESULT=$(gitlint --config cfg/gitlint/gitlint.cfg 2>&1) || exit_code=$?
  needs: [ ]