stages:
  - Lint

LintGitCommitMessages:
  stage: Lint
  image:
    name: jorisroovers/gitlint:0.19.1
    entrypoint: [ "" ]
  script:
    - exit_code=0
    - RESULT=$(gitlint --config cfg/gitlint/gitlint.cfg 2>&1) || exit_code=$?
    - handle_test_result $exit_code "$RESULT"
    - exit $exit_code
  needs: [ ]