stages:
  - generate-config
  - lint

GenerateGitlintConfig:
  stage: generate-config
  script:
    - echo "TEST"
  artifacts:
    paths:
      - gitlint.cfg

LintGitCommitMessages:
  stage: lint
  only:
    - main
  dependencies:
    - GenerateGitlintConfig
  image:
    name: python:3.9-slim
    entrypoint: [""]
  script:
    - apt-get update && apt-get install -y curl git
    - pip install gitlint
    - |      
      echo "Downloading gitlint.cfg from the ci-commons project..."
      curl --header "PRIVATE-TOKEN: $CI_PERSONAL_ACCESS_TOKEN" --output gitlint.cfg "${CI_API_V4_URL}/projects/fabien.launay.public%2Fci-commons/jobs/artifacts/main/raw/gitlint.cfg?job=GenerateGitlintConfig"
    - gitlint --config gitlint.cfg