stages:
  - generate-config
  - lint

GenerateGitlintConfig:
  stage: generate-config
  script:
    - echo "TEST"
  artifacts:
    paths:
      - cfg/gitlint/gitlint.cfg

LintGitCommitMessages:
  stage: lint
  only:
    - main
  dependencies:
    - GenerateGitlintConfig
  image:
    name: python:3.9-slim
    entrypoint: [""]
  script:
    - apt-get update && apt-get install -y curl git
    - pip install gitlint
    - |
      if [ ! -f cfg/gitlint/gitlint.cfg ]; then
        echo "Downloading cfg/gitlint/gitlint.cfg from the ci-commons project..."
        mkdir -p cfg/gitlint
        curl --header "PRIVATE-TOKEN: $CI_PERSONAL_ACCESS_TOKEN" --output cfg/gitlint/gitlint.cfg "${CI_API_V4_URL}/projects/fabien.launay.public%2Fci-commons/jobs/artifacts/main/raw/cfg/gitlint/gitlint.cfg?job=GenerateGitlintConfig"
      fi
    - gitlint --config cfg/gitlint/gitlint.cfg