stages:
  - generate-config
  - lint

GenerateGitlintConfig:
  stage: generate-config
  script:
    - echo "TEST"
  artifacts:
    paths:
      - cfg/gitlint/

LintGitCommitMessages:
  stage: lint
  only:
    - main
  dependencies:
    - GenerateGitlintConfig
  image:
    name: python:3.9-slim
    entrypoint: [""]
  script:
    - apt-get update && apt-get install -y curl git
    - pip install gitlint
    - |
      if [ ! -f cfg/gitlint/gitlint.cfg ]; then
        echo "Downloading cfg/gitlint/gitlint.cfg from the ci-commons project..."        
        curl \
          --header "PRIVATE-TOKEN: $CI_PERSONAL_ACCESS_TOKEN" \
          --output artifacts.zip \
          "${CI_API_V4_URL}/projects/fabien.launay.private%2Fci-commons/jobs/artifacts/main/download?job=GenerateGitlintConfig"
        unzip artifacts.zip
        ls -lR cfg
      fi
    - gitlint --config cfg/gitlint/gitlint.cfg