################################################################################
# Pipeline Stages Definition
################################################################################
stages:
  - lint
  - check
  - build