name: CI commons

run-name: CI commons

on:
  # Trigger on push to the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allow this workflow to be called as a reusable workflow
  workflow_call:
    inputs: {}

jobs:
  Lint-ci-commons-project:
    runs-on: "ubuntu-latest"
    if: github.repository == 'FabienLaunay/ci-commons' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install -y git
          pip install gitlint

      - name: Run gitlint
        run: gitlint --config cfg/gitlint/gitlint.cfg

  Lint:
    runs-on: "ubuntu-latest"
    if: github.repository != 'FabienLaunay/ci-commons' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install -y curl unzip git
          pip install gitlint

      - name: Download artifacts
        run: |
          echo "Downloading artifacts.zip from 'ci-commons' project..."
          echo "####################"
          echo ${{ secrets.CI_COMMONS_PAT }}
          echo ${{ CI_COMMONS_PAT }}
          echo "####################"
          mkdir -p cfg/gitlint
          curl \
            --location \
            --header "Authorization: token ${{ secrets.CI_COMMONS_PAT }}" \
            --output cfg/gitlint/gitlint.cfg \
             https://raw.githubusercontent.com/FabienLaunay/ci-commons/main/cfg/gitlint/gitlint.cfg
          mkdir -p cfg/gitlint/rules
          curl \
            --location \
            --header "Authorization: token ${{ secrets.CI_COMMONS_PAT }}" \
            --output cfg/gitlint/rules/TitleImperativeMood.py \
             https://raw.githubusercontent.com/FabienLaunay/ci-commons/main/cfg/gitlint/rules/TitleImperativeMood.py
          curl \
            --location \
            --header "Authorization: token ${{ secrets.CI_COMMONS_PAT }}" \
            --output cfg/gitlint/rules/TitleVerbCapitalized.py \
             https://raw.githubusercontent.com/FabienLaunay/ci-commons/main/cfg/gitlint/rules/TitleVerbCapitalized.py
          mkdir -p cfg/gitlint/txt
          curl \
            --location \
            --header "Authorization: token ${{ secrets.CI_COMMONS_PAT }}" \
            --output cfg/gitlint/txt/Verbs.txt \
             https://raw.githubusercontent.com/FabienLaunay/ci-commons/main/cfg/gitlint/txt/Verbs.txt
          ls -lR cfg

      - name: Run gitlint
        run: gitlint --config cfg/gitlint/gitlint.cfg

  Generate_artifacts:
    runs-on: "ubuntu-latest"
    needs: Lint-ci-commons-project
    if: github.repository == 'FabienLaunay/ci-commons' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: cfg/gitlint/