name: CI commons

run-name: CI commons

on:
  # Trigger on push to the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allow this workflow to be called as a reusable workflow
  workflow_call:
    inputs: {}

jobs:
  Lint-ci-commons-project:
    runs-on: "ubuntu-latest"
    if: github.repository == 'FabienLaunay/ci-commons' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install -y git
          pip install gitlint

      - name: Run gitlint
        run: gitlint --config cfg/gitlint/gitlint.cfg

  Generate_artifacts:
    runs-on: "ubuntu-latest"
    needs: Lint-ci-commons-project
    if: github.repository == 'FabienLaunay/ci-commons' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: cfg/gitlint/