name: CI Commons

on:
  # Trigger on push to the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allow this workflow to be called as a reusable workflow
  workflow_call:
    inputs: {}

jobs:
  Lint-ci-commons-project:
    runs-on: "ubuntu-latest"
    if: github.repository == 'FabienLaunay/ci-commons' && github.ref == 'refs/heads/main'
    steps:
      - name: STEP 1 of 6 - Checkout code
        uses: actions/checkout@v4

      - name: STEP 2 of 6 - Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: STEP 3 of 6 - Update Gitlab runner local package index
        run: sudo apt-get update

      - name: STEP 4 of 6 - Install 'git' Debian package
        run: sudo apt-get install -y git

      - name: STEP 5 of 6 - Install 'gitlint' Python package installation
        run: pip install gitlint

      - name: STEP 6 of 6 - Run gitlint
        run: gitlint --config cfg/gitlint/gitlint.cfg

  Lint:
    runs-on: "ubuntu-latest"
    if: github.repository != 'FabienLaunay/ci-commons' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install -y curl unzip git
          pip install gitlint

      - name: Download artifacts
        run: |
          echo "Downloading artifacts.zip from 'ci-commons' project..."
          mkdir -p cfg/gitlint
          curl \
            --location \
            --header "Authorization: token ${{ secrets.GITHUB_TOKEN  }}" \
            --output cfg/gitlint/gitlint.cfg \
             https://raw.githubusercontent.com/FabienLaunay/ci-commons/main/cfg/gitlint/gitlint.cfg
          mkdir -p cfg/gitlint/rules
          curl \
            --location \
            --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            --output cfg/gitlint/rules/TitleImperativeMood.py \
             https://raw.githubusercontent.com/FabienLaunay/ci-commons/main/cfg/gitlint/rules/TitleImperativeMood.py
          curl \
            --location \
            --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            --output cfg/gitlint/rules/TitleVerbCapitalized.py \
             https://raw.githubusercontent.com/FabienLaunay/ci-commons/main/cfg/gitlint/rules/TitleVerbCapitalized.py
          mkdir -p cfg/gitlint/txt
          curl \
            --location \
            --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            --output cfg/gitlint/txt/Verbs.txt \
             https://raw.githubusercontent.com/FabienLaunay/ci-commons/main/cfg/gitlint/txt/Verbs.txt

      - name: Run gitlint
        run: gitlint --config cfg/gitlint/gitlint.cfg

  Generate_artifacts:
    runs-on: "ubuntu-latest"
    needs: Lint-ci-commons-project
    if: github.repository == 'FabienLaunay/ci-commons' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: cfg/gitlint/